version: '3.1'

services:
  app:
    build:
      context: php/.
    container_name: ${PHP_CONTAINER_NAME}
    restart: always
    environment:
      USER_ID : ${USER_ID}
      GROUP_ID : ${GROUP_ID}
    volumes:
      - ./log/apache:/var/log/apache2
      - ../:/var/www/html
    networks:
       - traefik_network
    labels:
       - "traefik.enable=true"
       - "traefik.frontend.rule=Host:${HTTP_HOSTNAME}"
       - "traefik.port=80"
       - "traefik.backend=${TRAEFIK_HTTP_BACK_END}"
       - "traefik.frontend.entryPoints=http,https"
       - "traefik.frontend.redirect.entryPoint=https"

  db:
    image: mariadb
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
       - traefik_network
#    command: #--initialize-insecure #--max_allowed_packet=325058560 --innodb_use_native_aio = 0
    volumes:
      - ./mysql_data:/var/lib/mysql
    labels:
       - "traefik.enable=false"

networks:
  traefik_network:
    external: true
